// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab01.Models;

public partial class Course
{
    public int Id { get; set; }

    public string CrsName { get; set; }

    public string CrsDsc { get; set; }

    public int? Duration { get; set; }
}